version: "3"
services:
  express:
    image: node-docker:latest
    entrypoint: '/bin/sh -c'
    build: .
    working_dir: /work
    volumes:
      - ./../src:/work
    ports:
      - 8080:3000
    restart: always
  shell:
    image: node-docker:latest
    entrypoint: '/bin/sh'
    working_dir: /work 
    volumes:
      - ./../src:/work
  server:
    image: node-docker:latest
    entrypoint: '/bin/sh -c'
    working_dir: /work
    volumes:
      - ./../src:/work
    ports:
      - 3000:8080
    restart: always