version: "3"
services:
  web:
    image: "node:17-alpine3.12"
    entrypoint: '/bin/sh -c'
    build: .
    working_dir: /work
    volumes:
      - ./../src:/work
    ports:
      - 8080:3000
    restart: always